apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: okteto.dev/wordpress:5.8-fpm7.4-apache2
        name: wordpress
        
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: PORT
          value: "80"
