apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: okteto.dev/wordpress:latest
        name: wordpress
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
