apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "wordpress"
    port: 80
  selector:
    app: wordpress
