apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - protocol:tcp
    name: "http"
    port: 80
    targetPort:80
  selector:
    app: wordpress
