apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: wordpress
    port: 80
    targetPort: 80
  selector:
    app: wordpress
    tier: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels: 
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: okteto.dev/wordpress:5.8-fpm7.4-apache2
        name: frontend-wordpress
      env:
      - name: WORDPRESS_DB_HOST
        value: wordpress-mysql
     
      - name: WORDPRESS_DB_USER
        valueFrom:
          secretKeyRef:
              name: dbsecret
              key: username
      - name: WORDPRESS_DB_PASSWORD
        valueFrom:
           secretKeyRef:
              name: dbsecret
              name: dbsecret
              key: password
      ports:
      - containerPort: 80
         protocol: TCP  

