apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: zz.dev/wordpress:5.8-fpm7.4-apache2
        name: wordpress

        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: PORT
          value: "80"

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "wordpress"
    port: 80
    targetPort: 80
  selector:
    app: wordpress
